-- QS Tech MVP schema
CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(200),
  phone VARCHAR(100),
  budget DECIMAL(12,2) NULL,
  message TEXT,
  keywords VARCHAR(255),
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  jira_key VARCHAR(50),
  created_at DATETIME NOT NULL,
  CONSTRAINT fk_projects_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory (
  sku VARCHAR(120) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  qty INT NOT NULL DEFAULT 0,
  threshold INT NOT NULL DEFAULT 0,
  supplier VARCHAR(255),
  updated_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(120) NOT NULL,
  message VARCHAR(500) NOT NULL,
  status ENUM('open','cleared') NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_type VARCHAR(120) NOT NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
